# Generated by Django 5.2.12 on 2026-03-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("safety_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("logout", "Logout"),
                    ("register", "Register"),
                    ("login_rate_limited", "Login Rate Limited"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("admin_action", "Admin Action"),
                ],
                max_length=20,
            ),
        ),
    ]
