# Generated by Django 5.2.12 on 2026-03-09 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_type", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("servings", "Servings"),
                            ("kg", "Kilograms"),
                            ("liters", "Liters"),
                        ],
                        default="servings",
                        max_length=20,
                    ),
                ),
                ("preparation_time", models.DateTimeField()),
                ("expiry_time", models.DateTimeField(db_index=True)),
                ("freshness_score", models.FloatField(default=0.0)),
                ("pickup_address", models.CharField(max_length=500)),
                ("pickup_latitude", models.FloatField()),
                ("pickup_longitude", models.FloatField()),
                ("is_vegetarian", models.BooleanField(default=False)),
                ("is_vegan", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("allergen_info", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("reserved", "Reserved"),
                            ("completed", "Completed"),
                            ("expired", "Expired"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "available_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "food_listings",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expiry_time"], name="food_listin_expiry__86e8a9_idx"
                    ),
                    models.Index(
                        fields=["status"], name="food_listin_status_dd489b_idx"
                    ),
                    models.Index(
                        fields=["donor"], name="food_listin_donor_i_76ea2a_idx"
                    ),
                ],
            },
        ),
    ]
