# Generated by Django 5.2.12 on 2026-05-04 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_listings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodlisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Approval"),
                    ("available", "Available"),
                    ("reserved", "Reserved"),
                    ("completed", "Completed"),
                    ("expired", "Expired"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="available",
                max_length=20,
            ),
        ),
    ]
