# Generated by Django 5.2.12 on 2026-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receiver_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual"),
                    ("ngo", "NGO"),
                    ("shelter", "Shelter"),
                    ("orphanage", "Orphanage"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="verification_document",
            field=models.FileField(
                blank=True,
                help_text="Required for NGO, Shelter, and Orphanage receiver types",
                null=True,
                upload_to="verification_docs/",
            ),
        ),
    ]
