# Generated by Django 5.2.12 on 2026-03-09 17:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("food_listings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("pickup_time_preference", models.DateTimeField()),
                ("special_instructions", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="food_listings.foodlisting",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "food_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matched_quantity",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("matched", "Matched"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="matched",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donor_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="food_listings.foodlisting",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receiver_matches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="match",
                        to="matching.foodrequest",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="foodrequest",
            index=models.Index(
                fields=["listing"], name="food_reques_listing_8eaa55_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodrequest",
            index=models.Index(
                fields=["receiver"], name="food_reques_receive_84fb9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="foodrequest",
            index=models.Index(fields=["status"], name="food_reques_status_3b9363_idx"),
        ),
        migrations.AddConstraint(
            model_name="foodrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status", "pending"), ("status", "approved"), _connector="OR"
                ),
                fields=("listing", "receiver"),
                name="unique_active_request_per_listing_receiver",
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["status"], name="matches_status_639056_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["donor"], name="matches_donor_i_0b9f96_idx"),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(fields=["receiver"], name="matches_receive_9904b3_idx"),
        ),
    ]
