# Generated by Django 5.2.12 on 2026-05-04 07:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_listings", "0002_update_unique_request_constraint_pending_only"),
        ("matching", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="foodrequest",
            name="unique_active_request_per_listing_receiver",
        ),
        migrations.AddConstraint(
            model_name="foodrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("listing", "receiver"),
                name="unique_active_request_per_listing_receiver",
            ),
        ),
    ]
