# Generated by Django 5.2.12 on 2026-03-09 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("volunteers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_latitude", models.FloatField()),
                ("current_longitude", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("en_route_to_donor", "En Route to Donor"),
                            ("at_donor", "At Donor"),
                            ("en_route_to_receiver", "En Route to Receiver"),
                            ("delivered", "Delivered"),
                        ],
                        default="en_route_to_donor",
                        max_length=30,
                    ),
                ),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "coordination",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_tracking",
                        to="volunteers.pickupcoordination",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_trackings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "delivery_trackings",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["volunteer"], name="delivery_tr_volunte_f929f4_idx"
                    ),
                    models.Index(
                        fields=["status"], name="delivery_tr_status_216300_idx"
                    ),
                ],
            },
        ),
    ]
